### ISSUE TITLE
Design a logo for Connect 4

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#12]
- [ ] Create Vector Graphics. 
- [ ] Logo must not be copied.

**Comment by Xx-Ashutosh-xX** [comment]
I do have little experience in adobe illustrator , can I take it ?

**Comment by bymayanksingh** [comment]
sure @Xx-Ashutosh-xX

**Comment by Xx-Ashutosh-xX** [comment]
> sure @Xx-Ashutosh-xX

can we close this issue as there is already a logo present
