### ISSUE TITLE
design an aesthetic single page product launch website.

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#15]
you can take inspiration from: [studiovoila](https://studiovoila.com/) 
for an example this is main page for the same. 
![image](https://user-images.githubusercontent.com/19390263/70394057-11988680-1a17-11ea-9ada-35771fe54693.png)

website should be static.

**Comment by Shashvat6264** [comment]
I would like to work on this project.

**Comment by bymayanksingh** [comment]
@Shashvat6264 Sure ! please discuss if you have some queries.
