### ISSUE TITLE
Modify readme to mention about game features.

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#16]
make a new features section. 

which lists all of the following:

- [x] two player game
- [x] supports undo operation
- [x] supports interactive game sounds
- [ ] ability to play with computer AI (currently in development phase)
- [ ] multiplayer on local network using sockets. (in development phase)
- [ ] ability to customize game theme. (in development phase) 
- [ ] is cross platform `Linux, Windows, Mac` (in development phase)

**Comment by Satvinder31415** [comment]
Can I take this one?

**Comment by bymayanksingh** [comment]
sure, please go ahead @Satvinder31415
