### ISSUE TITLE
More than 2 players can play the game at once

### ISSUE THREAD

**Issue by Satvinder31415** [code-monk08/connect4#20]
More than 2 players can play the game at the same time with the same rules.In other words, the number of players is also generalized.For example, there may be 3 players red,blue and green each aiming to achieve 4 in a row on the same board.

**Comment by bymayanksingh** [comment]
@Satvinder31415 yes, but that won't be a rewarding experience for the player themselves, don't you think? like for instance most of the games will finish quickly or will end up in game draws.

**Comment by Satvinder31415** [comment]
I was thinking that when the game size has been generalized for large
boards we could implement this feature but I do understand your point.It's
fine if we remove it.

**Comment by bymayanksingh** [comment]
okay then, please close this issue, but as an extension keep suggesting new features.
