### ISSUE TITLE
BUG when a column gets filled

### ISSUE THREAD

**Issue by Xx-Ashutosh-xX** [code-monk08/connect4#21]
no error is shown if we again try to put another piece in that column rather it passes the turn to next player
![1](https://user-images.githubusercontent.com/58273769/70550305-8c8aaa00-1b9b-11ea-94eb-7b429b927c35.png)
![2](https://user-images.githubusercontent.com/58273769/70550303-8bf21380-1b9b-11ea-9883-a469408e2896.png)
![3](https://user-images.githubusercontent.com/58273769/70550304-8bf21380-1b9b-11ea-81f4-eb946eb91e7c.png)

**Comment by bymayanksingh** [comment]
Thank you @Xx-Ashutosh-xX for raising this issue. 
can you fix this and raise a PR ?

**Comment by Xx-Ashutosh-xX** [comment]
I will try to fix it

**Comment by KomalKalyan** [comment]
I have actualluy fixed this issue!

**Comment by bymayanksingh** [comment]
@Xx-Ashutosh-xX closing this issue, fix sent by @KomalKalyan was just merged.
can you take a look at #23 instead ? :)

**Comment by KomalKalyan** [comment]
Sure
