### ISSUE TITLE
Add more badges in readme.

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#23]
![image](https://user-images.githubusercontent.com/19390263/70553082-7e8b5800-1ba0-11ea-93db-23c1d6cef545.png)

- add FOLLOW CODE-MONK08 (github badge, take reference from twitter badge) 
- add [sourcerer.io](https://sourcerer.io/code-monk08) hall of fame for my profile. (take reference from bottom most section in this [readme](https://github.com/vinitshahdeo/jobtweets))

**Comment by Satvinder31415** [comment]
@code-monk08 can I take this one?

**Comment by bymayanksingh** [comment]
> @code-monk08 can I take this one?

let's  give chance to other contributors for this one :)

**Comment by Satvinder31415** [comment]
sure

**Comment by Shardul555** [comment]
@code-monk08 Can I try this one??

**Comment by bymayanksingh** [comment]
> @code-monk08 Can I try this one??

actually I have already asked someone else in the community to work on it.. waiting for his pull request.

**Comment by bymayanksingh** [comment]
@Cypre55 any updates?

**Comment by Cypre55** [comment]
Sorry was AFK for a while.
At it now

**Comment by Cypre55** [comment]
Hi
A doubt. Isn't the twitter badge already there in the start

**Comment by bymayanksingh** [comment]
Twitter badge is there but not the GitHub badge, I need a GitHub badge.

**Comment by bymayanksingh** [comment]
I am adding it, thanks :)
