### ISSUE TITLE
Add community section in readme

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#26]
follow this https://gist.github.com/ramantehlan/602ad8525699486e097092e4158c5bf1#cherry_blossom-community

don't add branches sub section, also mention about CODE_OF_CONDUCT file in project directory.

**Comment by Shardul555** [comment]
Hi , I will like to work on this issue..

**Comment by bymayanksingh** [comment]
Go ahead! @Shardul555

**Comment by Shardul555** [comment]
I am bit confused whether I have to make whole README.md file or else what to do .

**Comment by Shardul555** [comment]
I have made README with the required changes but I am getting difficulty with adding badges and some other things.

**Comment by bymayanksingh** [comment]
> I am bit confused whether I have to make whole README.md file or else what to do .

you have to add community section in exisiting readme.

**Comment by bymayanksingh** [comment]
> I have made README with the required changes but I am getting difficulty with adding badges and some other things.

don't make new file, leave this badge thing for now, open your PR then I will guide you.

**Comment by Shardul555** [comment]
i have opened my PR ,you can check for corrections

**Comment by bymayanksingh** [comment]
Thanks @Shardul555
