### ISSUE TITLE
Implement Game AI.

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#3]
Currently only two human users can play the game at once, design game AI for human vs computer experience, Use 

- [ ]  Min Max Algorithm.

**Comment by rdr42** [comment]
I will take this one.

**Comment by bymayanksingh** [comment]
@rdr42 sure, but can you first help in issue #2 :)

**Comment by adnansalik** [comment]
Can I work on this issue?

**Comment by bymayanksingh** [comment]
@adnansalik sure, please go ahead.

**Comment by bymayanksingh** [comment]
@adnansalik any updates?

**Comment by adnansalik** [comment]
I think I'll be implementing the min max algorithm and will send the code to you by Thursday if it's not a problem, if I get stuck somewhere I'll get in touch with you.

**Comment by bymayanksingh** [comment]
@adnansalik no problem, take your time.

**Comment by bymayanksingh** [comment]
@ajaykumarr123 @adnansalik please collaborate if it's okay with you both, if possible divide work and raise separate PR so that it counts for both of you.

**Comment by adnansalik** [comment]
@ajaykumarr123 is there a platform where we can communicate?

**Comment by bymayanksingh** [comment]
@adnansalik we have slack, you both can communicate there.

**Comment by adnansalik** [comment]
> @adnansalik we have slack, you both can communicate there.

I don't see his handle there

**Comment by ajaykumarr123** [comment]
@adnansalik sorry bro I wasn't aware of connect 4 slack channel.
 but  now, we can communicate there.

**Comment by adnansalik** [comment]
I have compiled an easy level AI using randint(). Can I send you over the code of that? I'm having some issues with the minimax algorithm while defining some functions which would be resolved by today but in the meantime can you merge the code after reviewing it?
