### ISSUE TITLE
Implement multiplayer gaming using sockets

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#4]
- [ ] Use Socket server.

**Comment by balindam** [comment]
Sir, is this issue open, can i take it?

**Comment by bymayanksingh** [comment]
@balindam it's open, please go ahead and take it. 
also we don't use sir/ma'am here.

**Comment by bymayanksingh** [comment]
@balindam any updates?

**Comment by 1llum1n4ti** [comment]
Yo balindam are you doing this still or no?
