### ISSUE TITLE
Use alternate approach for `restart.sh`

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#5]
- [ ] Give more controls to the user in the game window itself.

**Comment by agarwalshivani23** [comment]
can i work on this issue?

**Comment by bymayanksingh** [comment]
@agarwalshivani23 yes

**Comment by Satvinder31415** [comment]
I've started some work on this issue as well. If anyone else is working on it, I'll be happy to discuss and collaborate.

**Comment by agarwalshivani23** [comment]
Yeah sure

**Comment by Satvinder31415** [comment]
@code-monk08  @agarwalshivani23 
Hi, I've made some changes to implement the start menu and restart option. They're present in one of my repositories : connect4-2. Running main_menu.py will start the application(with a black screen currently).Pressing enter will launch the game.After the game is over,pressing y will restart while n will quit the game.Feel free to modify the code and add graphics(currently there are none). Also, bear in mind that this version is 2 commits behind the original one. I don't feel confident implementing graphics and mouse interactivity so I think that'll be the end of my contribution to this issue.

**Comment by bymayanksingh** [comment]
@Satvinder31415 do one thing push your branch, I will ask @agarwalshivani23 to continue work from there.

**Comment by bymayanksingh** [comment]
@Satvinder31415 but why are you feeling under confident?

**Comment by Satvinder31415** [comment]
No it's just that I'm not really good at front end design. I was thinking
of taking the test cases issue and working on it.

**Comment by bymayanksingh** [comment]
ahh ! no issues we can improve whatever you design.. after all it's all about being creative, I will suggest you to try your hand again at this issue, bare minimum graphics will also do :)

**Comment by Satvinder31415** [comment]
I'm currently doing unit testing. I'll come back to this.

**Comment by bymayanksingh** [comment]
@Satvinder31415 I have recently merged @agarwalshivani23 's pull request and I am closing this issue, if you still want to add start menu to the game then I am looking forward to your PR, you can check the updated code and look if it helps you.
