### ISSUE TITLE
give more functionality to user to change aesthetics of the game.

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#7]
- [ ] user can change color of coins.
- [ ] user can change game's grid color.

**Comment by Xx-Ashutosh-xX** [comment]
can I do work in this. I am new to this type of thing so this one looks like I can do it...

**Comment by bymayanksingh** [comment]
@Xx-Ashutosh-xX Go ahead.

**Comment by bymayanksingh** [comment]
you will have to design a bunch of new colored svg coins. 
you can straight away give the option to change color of the game board from blue to something else.
you can check if filling in a pattern instead of solid color can be achieved through pygame. (you will need to define those pattern)
at first you can assign a shortcut key to change the aesthetics randomly (I will suggest you this first, then you can integrate it with #9 )

**Comment by ajaykumarr123** [comment]
I would like to work on this project.

**Comment by bymayanksingh** [comment]
> I would like to work on this project.

please collaborate with @Xx-Ashutosh-xX

**Comment by ajaykumarr123** [comment]
ya thanks

**Comment by Xx-Ashutosh-xX** [comment]
sorry for not being to active @ajaykumarr123 , lets work on this issue together :)

**Comment by Xx-Ashutosh-xX** [comment]
I am currently working on a Start menu type of a thing where the user can change the colour of the coin.

**Comment by bymayanksingh** [comment]
@Xx-Ashutosh-xX :+1:

**Comment by ajaykumarr123** [comment]
I am also working on the same to provide user with an option to change coin colours

**Comment by bymayanksingh** [comment]
Great @ajaykumarr123

**Comment by Xx-Ashutosh-xX** [comment]
I am almost done with it ,but facing an issue and not able to exit menu loop to go into game loop

**Comment by Xx-Ashutosh-xX** [comment]
`from assets import (
    red_coin,
    yellow_coin,
    green_coin,
    blue_coin,
    violet_coin
)
from config import black,blue, red, white, yellow ,green ,violet ,blue_player
import pygame
from game_data import GameData


pygame.init()
data = GameData()
screen = pygame.display.set_mode(data.size)
screen.fill(black)


def button(msg,x,y,w,h,color,action=None):
    """
    function to make buttons that perform an action
    """
    mouse = pygame.mouse.get_pos()
    click = pygame.mouse.get_pressed()
    pygame.draw.rect(screen,color,(x,y,w,h))

    if x+w>mouse[0]>x and y+h>mouse[1]>y and click[0]==1 and action != None:
        if action == start or action == quit :
            action()
        else :
            action(color)

    FONT = pygame.font.Font("freesansbold.ttf",50)
    textSurf = FONT.render(msg, True, black)
    textRect = textSurf.get_rect()
    textRect.center = ((x+(w/2)),(y+(h/2)))
    screen.blit(textSurf,textRect)


def player_color(i,color):
    """
    used to make a list which specifies the coin player 1 & 2 are using
    """
    if i==0:
        if color == red:
            player_color_list[0]=red_coin
        elif color == yellow:
            player_color_list[0]=yellow_coin
        elif color == green:
            player_color_list[0]=green_coin
        elif color == blue_player:
            player_color_list[0]=blue_coin
        elif color == violet:
            player_color_list[0]=violet_coin
    if i==1:
        if color == red:
            player_color_list[1]=red_coin
        elif color == yellow:
            player_color_list[1]=yellow_coin
        elif color == green:
            player_color_list[1]=green_coin
        elif color == blue_player:
            player_color_list[1]=blue_coin
        elif color == violet:
            player_color_list[1]=violet_coin


def color_select_1(color):
    """
    used to select color for player 1
    """
    button("Player 1",100,150,200,50,color)
    player_color(0,color)   


def color_select_2(color):
    """
    used to select color for player 2
    """
    button("Player 2",100,350,200,50,color)
    player_color(1,color) 


button("Player 1",100,150,200,50,red)
button("Player 2",100,350,200,50,yellow)
player_color_list=[red_coin,yellow_coin]

def start():
    """
    used to start the game
    """
    intro = False

def quit():
    """
    used to quit the game
    """    
    exit()

def intro():
    """
    Intro Screen loop
    """
    intro = True
    while intro is True :
        pygame.event.get()
        button("SELECT COLORS",100,50,450,50,white,None)

        button("",100,220,30,30,red,color_select_1)
        button("",150,220,30,30,yellow,color_select_1)
        button("",200,220,30,30,green,color_select_1)
        button("",250,220,30,30,blue,color_select_1)
        button("",300,220,30,30,violet,color_select_1)
        
        button("",100,420,30,30,red,color_select_2)
        button("",150,420,30,30,yellow,color_select_2)
        button("",200,420,30,30,green,color_select_2)
        button("",250,420,30,30,blue,color_select_2)
        button("",300,420,30,30,violet,color_select_2)

        button("START !",100,530,195,50,green,start)
        button("QUIT",400,530,195,50,red,quit)
        pygame.display.update()


intro()

import game`

**Comment by Xx-Ashutosh-xX** [comment]
`from assets import (
    red_coin,
    yellow_coin,
    green_coin,
    blue_coin,
    violet_coin
)
from config import black,blue, red, white, yellow ,green ,violet ,blue_player
import pygame
from game_data import GameData


pygame.init()
data = GameData()
screen = pygame.display.set_mode(data.size)
screen.fill(black)


def button(msg,x,y,w,h,color,action=None):
    """
    function to make buttons that perform an action
    """
    mouse = pygame.mouse.get_pos()
    click = pygame.mouse.get_pressed()
    pygame.draw.rect(screen,color,(x,y,w,h))

    if x+w>mouse[0]>x and y+h>mouse[1]>y and click[0]==1 and action != None:
        if action == start or action == quit :
            action()
        else :
            action(color)

    FONT = pygame.font.Font("freesansbold.ttf",50)
    textSurf = FONT.render(msg, True, black)
    textRect = textSurf.get_rect()
    textRect.center = ((x+(w/2)),(y+(h/2)))
    screen.blit(textSurf,textRect)


def player_color(i,color):
    """
    used to make a list which specifies the coin player 1 & 2 are using
    """
    if i==0:
        if color == red:
            player_color_list[0]=red_coin
        elif color == yellow:
            player_color_list[0]=yellow_coin
        elif color == green:
            player_color_list[0]=green_coin
        elif color == blue_player:
            player_color_list[0]=blue_coin
        elif color == violet:
            player_color_list[0]=violet_coin
    if i==1:
        if color == red:
            player_color_list[1]=red_coin
        elif color == yellow:
            player_color_list[1]=yellow_coin
        elif color == green:
            player_color_list[1]=green_coin
        elif color == blue_player:
            player_color_list[1]=blue_coin
        elif color == violet:
            player_color_list[1]=violet_coin


def color_select_1(color):
    """
    used to select color for player 1
    """
    button("Player 1",100,150,200,50,color)
    player_color(0,color)   


def color_select_2(color):
    """
    used to select color for player 2
    """
    button("Player 2",100,350,200,50,color)
    player_color(1,color) 


button("Player 1",100,150,200,50,red)
button("Player 2",100,350,200,50,yellow)
player_color_list=[red_coin,yellow_coin]

def start():
    """
    used to start the game
    """
    intro = False

def quit():
    """
    used to quit the game
    """    
    exit()

def intro():
    """
    Intro Screen loop
    """
    intro = True
    while intro is True :
        pygame.event.get()
        button("SELECT COLORS",100,50,450,50,white,None)

        button("",100,220,30,30,red,color_select_1)
        button("",150,220,30,30,yellow,color_select_1)
        button("",200,220,30,30,green,color_select_1)
        button("",250,220,30,30,blue,color_select_1)
        button("",300,220,30,30,violet,color_select_1)
        
        button("",100,420,30,30,red,color_select_2)
        button("",150,420,30,30,yellow,color_select_2)
        button("",200,420,30,30,green,color_select_2)
        button("",250,420,30,30,blue,color_select_2)
        button("",300,420,30,30,violet,color_select_2)

        button("START !",100,530,195,50,green,start)
        button("QUIT",400,530,195,50,red,quit)
        pygame.display.update()


intro()

import game`

**Comment by ajaykumarr123** [comment]
are you creating new screen for colour change or providing options in starting screen?

**Comment by ajaykumarr123** [comment]
![Screenshot from 2019-12-18 01-26-09](https://user-images.githubusercontent.com/45140292/71029342-34245100-2135-11ea-8cee-906e0eab6f2f.png)
![Screenshot from 2019-12-18 02-37-03](https://user-images.githubusercontent.com/45140292/71034245-0217ec80-213f-11ea-9aa2-06556b249d21.png)

@code-monk08 is it looking fine check once and any suggestion??

**Comment by ajaykumarr123** [comment]
![Screenshot from 2019-12-18 02-32-19](https://user-images.githubusercontent.com/45140292/71033969-5e2e4100-213e-11ea-8db0-e9ada67a1084.png)

**Comment by Xx-Ashutosh-xX** [comment]
I am thinking of something like a window where the users select their colours and then proceed   
![Screenshot (7)](https://user-images.githubusercontent.com/58273769/71042790-bc651f00-2152-11ea-9c9f-d42727ec5f44.png)

**Comment by bymayanksingh** [comment]
> are you creating new screen for colour change or providing options in starting screen?

you can provide options in starting screen itself, keep the current design consistent.

**Comment by ajaykumarr123** [comment]
@code-monk08 I mean color change option on starting page and different color, save option in new screen as shown in previous screenshots.

**Comment by Xx-Ashutosh-xX** [comment]
> are you creating new screen for colour change or providing options in starting screen?
> 
> you can provide options in starting screen itself, keep the current design consistent.

Let's just keep one screen where a player could change their colour then start the game

**Comment by ajaykumarr123** [comment]
I think that save option would be more proper for this and after press save button go back to starting page

**Comment by bymayanksingh** [comment]
> Let's just keep one screen where a player could change their colour then start the game

I completely agree with this.

**Comment by ajaykumarr123** [comment]
@code-monk08 I have completed first part and opened a PR #35 .

**Comment by Xx-Ashutosh-xX** [comment]
@code-monk08 I modified ajay's code and opened a PR #38 
I have combined everything in one screen and also added the logo

**Comment by ajaykumarr123** [comment]
@code-monk08 @Xx-Ashutosh-xX ya, I was thinking the same btw thanks for modification.

**Comment by ajaykumarr123** [comment]
@code-monk08 please check the PR's ASAP.
