### ISSUE TITLE
Implement new game window

### ISSUE THREAD

**Issue by bymayanksingh** [code-monk08/connect4#9]
Window that can

- [x] act as an entry point for users to start the game
- [ ] take names from player 1 and player 2
- [x] after the game is either over or the game draws, then this window will be shown and users can restart game from here itself. (thus solving issue #5 )

**Comment by KomalKalyan** [comment]
Can I take this issue?

**Comment by bymayanksingh** [comment]
@KomalKalyan sure, go ahead.

**Comment by Satvinder31415** [comment]
I've started some work on this issue as well. If anyone else is working on it, I'll be happy to discuss and collaborate.

**Comment by bymayanksingh** [comment]
@Satvinder31415 @KomalKalyan any updates?

**Comment by Satvinder31415** [comment]
I have implemented the restart option (via keyboard input). I am currently working on the start menu implementation and making the restart menu have clickable buttons. Will keep you updated on the progress.

**Comment by KomalKalyan** [comment]
Right now a bit busy but working on it!Thanks for helping😁

**Comment by Satvinder31415** [comment]
@code-monk08  @KomalKalyan  
Hi, I've made some changes to implement the start menu and restart option. They're present in one of my repositories : connect4-2. Running main_menu.py will start the application(with a black screen currently).Pressing enter will launch the game.After the game is over,pressing y will restart while n will quit the game.Feel free to modify the code and add graphics(currently there are none). Also, bear in mind that this version is 2 commits behind the original one. I don't feel confident implementing graphics and mouse interactivity so I think that'll be the end of my contribution to this issue.

**Comment by bymayanksingh** [comment]
pull request made by @agarwalshivani23 was merged, closing this issue.
If someone has additional features which are not in the current merged code, please feel free to add them.
